### ISSUE TITLE
Error : object has no attribute 

### ISSUE THREAD

**Issue by abdullah-3337** [abdelrahmanzied/AI-Virtual-Painter#1]
I have got an error while trying to run the code .. 
Here's the error  message :  :  : 
`  [ WARN:0] global /tmp/pip-req-build-ddpkm6fn/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
Traceback (most recent call last):
  File "/home/abdullah35/Documents/PycharmProjects/pythonProject3/main.py", line 236, in <module>
    imgResult = img.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
`

**Comment by abdelrahmanzied** [comment]
You should choose your camera, If you run with a laptop or default camera search in the core "default camera", activate this line and deactivate the line of "secondary camera". If you will use your phone with "IP Camera", deactivate the last both and activate "IP Camera". Enjoy!
